export const SITE_URL =
  process.env.NEXT_PUBLIC_SITE_URL?.replace(/\/$/, "") ||
  "https://dotku-studio.jytech.us";

export const BRAND = {
  name: "DotKu Studio",
  parentName: "JY Tech LLC",
  legalName: "JY Tech LLC",
  tagline: "AI-Powered Business Solutions",
  foundingYear: 2013,
  locality: "San Francisco Bay Area",
  country: "US",
  github: "https://github.com/dotku",
  email: "leo.liu@jytech.us",
  consultingUrl: "https://consulting.jytech.us/",
};

export const KEYWORDS_BY_LOCALE: Record<string, string[]> = {
  en: [
    "AI business solutions",
    "custom LLM",
    "enterprise software development",
    "Next.js consulting",
    "multilingual e-commerce",
    "technical due diligence",
    "San Francisco Bay Area studio",
    "open source",
    "JY Tech",
    "DotKu Studio",
  ],
  zh: [
    "AI 商业解决方案",
    "企业软件开发",
    "定制 LLM",
    "Next.js 外包",
    "多语言电商",
    "技术尽调",
    "旧金山湾区",
    "开源",
    "JY Tech",
    "DotKu Studio",
  ],
  "zh-TW": [
    "AI 商業解決方案",
    "企業軟體開發",
    "客製 LLM",
    "Next.js 外包",
    "多語系電商",
    "技術盡調",
    "舊金山灣區",
    "開源",
    "JY Tech",
    "DotKu Studio",
  ],
  es: [
    "Soluciones de negocio con IA",
    "LLM personalizado",
    "desarrollo software empresarial",
    "consultoría Next.js",
    "e-commerce multilingüe",
    "due diligence técnica",
    "estudio San Francisco Bay Area",
    "open source",
    "JY Tech",
    "DotKu Studio",
  ],
  ko: [
    "AI 비즈니스 솔루션",
    "커스텀 LLM",
    "엔터프라이즈 소프트웨어",
    "Next.js 컨설팅",
    "다국어 이커머스",
    "기술 실사",
    "샌프란시스코 베이 에어리어",
    "오픈소스",
    "JY Tech",
    "DotKu Studio",
  ],
  ja: [
    "AI ビジネスソリューション",
    "カスタム LLM",
    "エンタープライズ開発",
    "Next.js 開発",
    "多言語 EC",
    "技術デューデリジェンス",
    "サンフランシスコ・ベイエリア",
    "オープンソース",
    "JY Tech",
    "DotKu Studio",
  ],
};

export const OG_LOCALES: Record<string, string> = {
  en: "en_US",
  zh: "zh_CN",
  "zh-TW": "zh_TW",
  es: "es_ES",
  ko: "ko_KR",
  ja: "ja_JP",
};
